### ISSUE TITLE
TXT dosyası nerede?

### ISSUE THREAD

**Issue by koksal55** [ahmetcerol/Knapsack-Problem#1]
Merhaba. TXT dosyası yok, yardımcı olablir msin?

**Comment by ahmetcerol** [comment]
Merhabalar, benimde elimde sadece dosya uzunluğu 19 olan veri kalmış. Fakat mantığı aynı olduğu için Yapay Zeka araçlarına diğer örnekler içinde veri oluşturtabilirsiniz. Uzunluğu 19 olan veriyi ekliyorum. 4, 19, 200 ve 10000 diğer .txt dosyalarının uzunluğu.
[ks_19_0.txt](https://github.com/ahmetcerol/Knapsack-Problem/files/13599570/ks_19_0.txt)

**Comment by koksal55** [comment]
Teşekkür ederim
